### ISSUE TITLE
Job exception is not propagated to the shell

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-job#6] opened 2016-05-26 14:42 UTC
```
$ java -jar target/myapp-0.1.0.jar  --exec --job=myjob
[Exception is thrown by 'myjob']

$ echo $?
0
```

Exist code should reflect the error.

**Comment by atomashpolskiy** [comment] 2017-10-19 12:16
Closing this as duplicate of more recent #43

**Closed by atomashpolskiy** 2017-10-19 12:16 UTC
Labels: bug
